### ISSUE TITLE
Return 409 when syncing large folder

### ISSUE THREAD

**Issue by pbtrung** [graveljp/smugcli#1]
It failed to sync many folders when their parent folder has more than 200 entries because of paging (count=100000 does not work. Only returns max 200 entries).

The program is quite nice. Maybe the only one can recursively sync from local to remote for SmugMug. Just need more testing.
Thanks.

**Comment by graveljp** [comment]
Paging support implemented!
My unit-tests do have a few gaps, so I hope I did not break anything. I'll work on improving test coverage in a follow-up CL.
