### ISSUE TITLE
Folder path

### ISSUE THREAD

**Issue by pbtrung** [graveljp/smugcli#10]
Before:
`./smugcli.py sync /absolute/path/to/folderA -t Pics`
`folderA ` will be a subfolder of `Pics`

Now:
`./smugcli.py sync /absolute/path/to/folderA -t Pics`
`/absolute/path/to/folderA` will be a subfolder of `Pics`, which is prone to go over SmugMug limit.

**Comment by graveljp** [comment]
I updated the sync command source and destination arguments to match the program 'rsync'. The -t/--target is no longer needed, the last positional argument is always the destination. I also added a confirmation message, to avoid surprises for those not expecting a change in behavior. You can bypass this confirmation by adding -f/--force to the command line.

I updated SmugCLI Documentation as follows:

Multiple sources can be synced in the same operation, the last argument being the destination folder and the others being the sources:

$ ./smugcli.py sync 2016 2017 2018 remote/folder
Syncing:
  2016
  2017
  2018
to SmugMug folder "remote/folder"',
...

$ ./smugcli.py sync 201* remote/folder
...

Source files are synced to the destination SmugMug album and source folders are recursively synced to the destination SmugMug folder. For source folders with a trailing path delimitor ('/' or '\' depending on OS), only the content of the folder is synced, skipping the folder itself (equivalent of doing folder/*). This means that smugcli.py sync src/album dst is equivalent to smugcli.py sync src/album/ dst/album. If no sources or destinations are specified, smugcli defaults to syncing the current folder to the SmugMug user's root.
