### ISSUE TITLE
login error : AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by julzKB** [graveljp/smugcli#15]
I am getting this error when trying to login .
Any clues ? 

------------------

> 
> Started local server.
> Visit http://localhost:63983/ to grant SmugCli access to your SmugMug account.
> Opening page in default browser...
> Traceback (most recent call last):
>   File "/usr/local/bin/smugcli", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/smugcli/smugcli.py", line 299, in main
>     run(sys.argv[1:])
>   File "/usr/local/lib/python3.9/site-packages/smugcli/smugcli.py", line 291, in run
>     parsed.func(parsed)
>   File "/usr/local/lib/python3.9/site-packages/smugcli/smugcli.py", line 59, in <lambda>
>     login_parser.set_defaults(func=lambda a: fs.smugmug.login((a.key, a.secret)))
>   File "/usr/local/lib/python3.9/site-packages/smugcli/smugmug.py", line 383, in login
>     self.config['access_token'] = self.service.request_access_token()
>   File "/usr/local/lib/python3.9/site-packages/smugcli/smugmug_oauth.py", line 71, in request_access_token
>     while thread.isAlive():
> AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by graveljp** [comment]
I have not yet tested SmugCLI with Python 3.9. Do you also have the problem with Python 3.8?

**Comment by julzKB** [comment]
nope, working fine under python3.8 :) 
thank you !
