### ISSUE TITLE
submit to smugmug third-party uploaders

### ISSUE THREAD

**Issue by smoser** [graveljp/smugcli#30]
Thanks so much for this, its really wonderful. I had more than 80G of photos in a [menalto gallery](http://gallery.menalto.com/) that needed moved to smugmug.  This worked great.

You should submit this to smugmug so it shows up on their [Third party uploaders](https://help.smugmug.com/third-party-uploaders-downloaders-migration-tools-and-utilities-r11dlxDJNBz) page.

To do so, it says:

> Want to get your app listed on this page? Email api@smugmug.com for approval.

**Comment by graveljp** [comment]
I did send them an email and they never replied. Maybe it's time to ping them again.
