### ISSUE TITLE
Quiet mode ?

### ISSUE THREAD

**Issue by julzKB** [graveljp/smugcli#31]
Hi,
I was wondering if it would be possible to add a "quiet/shy" mode so it doesn't ask if you want to proceed with the sync and just does it . Handy if you have sync running as a cron job .

Merci beaucoup

**Comment by graveljp** [comment]
I think that what you are looking for is `-f` or `--force`:
https://github.com/graveljp/smugcli/blob/d8028fe8bbb23a027a5014eeb06031c927476c35/smugcli/smugcli.py#L224-L227

**Comment by julzKB** [comment]
perfect, thank you :)
