### ISSUE TITLE
File type support

### ISSUE THREAD

**Issue by pbtrung** [graveljp/smugcli#5]
SmugMug supports PNG, JPEG, and GIF.

**Comment by graveljp** [comment]
Done.
I also added a new ```media_extensions``` entry in the ```~/.smugcli``` config file, allowing users to choose the set of file extensions they want to sync with SmugMug. For instance, to sync videos only:

```
{
  "access_token": [...],
  "api_key": [...],
  "media_extensions": [".mov", ".mp4"]
}
```
