### ISSUE TITLE
Bug: Folder with both images and subfolders

### ISSUE THREAD

**Issue by pbtrung** [graveljp/smugcli#7]
When syncing a folder with both images and subfolders, this program only uploads the images and ignores the subfolders. 
The SmugMug web uploader works fine: create a new gallery for the "outside" images and upload the subfolders.

**Comment by graveljp** [comment]
I updated the sync operation to create an album "Images from folder X" for a folder X containing images and sub-folders. This is how the SmugMug built-in web upload handles this.
